"""empty message

Revision ID: 1adfe53dcd5b
Revises: 72eb5aa0b7bb
Create Date: 2021-02-25 08:45:11.311869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1adfe53dcd5b'
down_revision = '72eb5aa0b7bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('stock', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'stock')
    # ### end Alembic commands ###
